name: Update zets
on:
  repository_dispatch:
    types: [update-zet]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir $GITHUB_WORKSPACE/out
          cd $GITHUB_WORKSPACE/out
          git clone https://isaacguerreir:${{ secrets.TOKEN }}@github.com/isaacguerreir/zet.git 
      - run: bash $GITHUB_WORKSPACE/.github/scripts/copy-public
      - run: bash $GITHUB_WORKSPACE/.github/scripts/get-posts-metadata
      - run: bash $GITHUB_WORKSPACE/.github/scripts/build-readme
      - run: rm -rf $GITHUB_WORKSPACE/out
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff-index --cached --quiet HEAD || git commit -m "Update zets"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: prime
          repository: isaacguerreir/openzet
      - uses: actions/checkout@v3

 
